spring:
  config:
    activate:
      on-profile: local
  application:
    name: himart-clone-back
  messages:
    basename: messages,errors
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/himartclone
    url: jdbc:h2:mem:himartclone;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
#    open-in-view: false

logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: true

file:
  dir: C:\\User\\kkk26\\study\\file\\

app:
  prop:
    main-domain-url: loc.e-himart.co.kr:9730
    resource-domain-url: static1loc.e-himart.co.kr:9730
    profile: local

---

spring:
  config:
    activate:
      on-profile: staging

app:
  prop:
    profile: staging
    main-domain-url: tst.e-himart.co.kr
    resource-domain-url: static1tst.e-himart.co.kr

---

spring:
  config:
    activate:
      on-profile: production

app:
  prop:
    profile: staging
    main-domain-url: www.e-himart.co.kr
    resource-domain-url: static1tst.e-himart.co.kr