spring:
  application:
    name: himart-clone-back

  datasource:
    url: jdbc:h2:tcp://localhost/~/himartclone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
#    open-in-view: false

logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
